FROM php:7.1-apache

RUN docker-php-ext-install mysqli

RUN apt-get update && \
  apt-get install -y msmtp msmtp-mta && \
  apt-get clean

COPY container-conf-files/msmtprc /etc/msmtprc

# Memory Limit
RUN echo "memory_limit=1024M" > $PHP_INI_DIR/conf.d/memory-limit.ini
