FROM php:7.2-fpm

RUN docker-php-ext-install mysqli

RUN apt-get update && \
  apt-get install -y msmtp msmtp-mta && \
  apt-get clean

COPY msmtprc /etc/msmtprc

# Memory Limit
RUN echo "memory_limit=1024M" > $PHP_INI_DIR/conf.d/memory-limit.ini

# MySQLi Reconnect
RUN echo "[MySQLi]" > $PHP_INI_DIR/conf.d/mysqli-reconnect.ini
RUN echo "mysqli.reconnect=on" >> $PHP_INI_DIR/conf.d/mysqli-reconnect.ini
